### ISSUE TITLE
Expose more dnsPacket features in web interface

### ISSUE THREAD

**Issue by jacobgb24** [byu-imaal/dohjs#12]
* DNSSEC_OK and ECS seem to be supported by dohjs already so those should be fairly easy.
* Bonus features would be adding arbitrary EDNS option (similar to dig with (opt_code, payload) tuples)
* Anything else outside of EDNS that could be beneficial? It gets tricky with adding features, but not going overboard allowing manipulation of every bit
* Could probably put these in an "advanced" drop down

**Comment by kimbo** [comment]
>DNSSEC_OK and ECS seem to be supported by dohjs already so those should be fairly easy.

I moved the functionality for those two things out of dohjs and into the command line tool. Mostly because that was the only place they were being used. But agreed, it's very easy to add those in.

>Bonus features would be adding arbitrary EDNS option (similar to dig with (opt_code, payload) tuples)
Anything else outside of EDNS that could be beneficial? It gets tricky with adding features, but not going overboard allowing manipulation of every bit
Could probably put these in an "advanced" drop down

I think this is a good idea. Whatever functionality/options we add in here should probably be added to the cli as well.

Having an option for checking disabled (CD) flag might be good.

As far as EDNS options go, COOKIE and PADDING would probably be good. Adding padding would be pretty easy. Not sure how difficult COOKIE would be, but it'd be interesting no doubt.
