### ISSUE TITLE
Only works on node 10 or later

### ISSUE THREAD

**Issue by bramevo** [byu-imaal/dohjs#48]
Apparently it only works starting from node v10

ReferenceError: URL is not defined
    at Promise (..../node_modules/dohjs/lib/index.js:175:5)

**Comment by kimbo** [comment]
Correct, URL is only globally defined in node 10+. The fix for that is to add something like `var URL = require('url').URL` at the top of the page. I tried that before (see https://github.com/byu-imaal/dohjs/commit/6889d9a72e2875a2905a6cd3fca2eabb36487926) but for some reason it broke things and so I reverted the change (see https://github.com/byu-imaal/dohjs/commit/b5529b9b8894dbbde1389a4dd79414ea5a9e4c64). Don't remember what the exact issue was.

I'll take a look at it sometime in the next few days.

**Comment by bramevo** [comment]
Or you could add a warning in the README. Or a specific branch that has the require line for older versions.
